# Automation for building the Docker Image
name: Docker Image Build

# Trigger on new version release
on:
  push:
    tags:
      - v[0-9].[0-9].[0-9]

# Build and Push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push GNU
        id: docker_build_gnu
        uses: docker/build-push-action@v2
        with:
          push: true
          env:
            COMPILER=gnu
          build-args: COMPILER=$COMPILER
          tags: ${{ format('chargje/setsm_fork:latest-{1}, chargje/setsm_fork:{0}-{1}', steps.get_version.outputs.VERSION), $COMPILER }}
      -
        name: Build and push Intel
        id: docker_build_intel
        uses: docker/build-push-action@v2
        with:
          push: true
          env:
            COMPILER=intel
          build-args: COMPILER=$COMPILER
          tags: ${{ format('chargje/setsm_fork:latest-{1}, chargje/setsm_fork:{0}-{1}', steps.get_version.outputs.VERSION), $COMPILER }}
      -
        name: Build and push Cray
        id: docker_build_cray
        uses: docker/build-push-action@v2
        with:
          push: true
          env:
            COMPILER=cray
          build-args: COMPILER=$COMPILER
          tags: ${{ format('chargje/setsm_fork:latest-{1}, chargje/setsm_fork:{0}-{1}', steps.get_version.outputs.VERSION), $COMPILER }}
      