# Automation for building the Docker Image
name: Docker Image Build

# Trigger on new version release
on:
  push:
    tags:
      - v[0-9].[0-9].[0-9]

# Build and Push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get the version
        id: get_version
        run: echo ::set-ouput name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ format('chargje/setsm_fork:latest, chargje/setsm_fork:{0}', steps.get_version.outputs.VERSION) }}